[package]
name = "asm-cli-rust"
version = "0.1.0"
authors = ["Xargin <cao1988228@163.com>"]
edition = "2018"

[dependencies]
capstone = "^0.5.0"
keystone = "0.9.0"
unicorn = "0.9.0"
hex = "0.3.2"
rustyline = "5.0.5"
ansi_term = "0.11.0"
